### ISSUE TITLE
route which will get the conversation id for a specific set of recipients

### ISSUE THREAD

**Issue by codeHatcher** [codeHatcher/lightTribe#100]

**Comment by codeHatcher** [comment]
@ShadiFares @footnote we are giving you the entire conversation along with the populated message and imageIds. It's more than you asked for (you asked for the conversation id) but I think this might be the better way to do it. If you have no use for the extra fields you can just ignore it.

**Comment by footnote** [comment]
I am assuming we get a null if there is no conversation id for a specific user. correct?
