### ISSUE TITLE
Unable to see the full history of a conversation

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#101]
Only the recipient part of the conversation is returned. 
GET /v1/conversations/{conversationId}

Use the following testing data to replicate
conversation ID:  561868405007f27302e00c9d
access token: S362u7bFRqRvJo53Zv

**Comment by codeHatcher** [comment]
We think we found the bug however it won't work for old conversations. New conversations will need to be created in order for this to work. Please check this out with new conversations and see if the same issue is occurring.
