### ISSUE TITLE
Need a route to retrieve keywords to categorize a post as well as update a post category

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#107]
Also, please confirm that the workflow would be that for every new post after a user completes a post the app will parse the post's description, compare the text to the keywords and present a user with a screen of categories checked related to that post based on all matches between the keywords and the text. if not match no keyword will be checked. upon user's confirmation the front end will call a route to update a post category. this will be mandatory.

**Comment by avishaan** [comment]
I don't understand the last part of this. What do you mean by "upon user's confirmation the front end will call a route to update a post category". Why would the front end need to ever update a post category upon front end confirmation. It should set the categories before creating the post to begin with.

@ShadiFares @footnote The backend will have to add another property called "keywords" which will be an array of strings. Will that break anything on the front end?

**Comment by avishaan** [comment]
It looks like if a property is added to the backend the front end continues to respond normally which means the backend can proceed independently

**Comment by footnote** [comment]
ok.

**Comment by footnote** [comment]
Meant to say we will enforce the need to categorize a post and it will not be optional for the user to bypass. Will check with the team the workflow, but don't see what you suggested as not feasible . We still will need a route to retrieve keywords

**Comment by avishaan** [comment]
keywords are being sent back
