### ISSUE TITLE
Route to post GUID to link a user

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#32]
We need a route to post the GUID of a device so that not logged in user can use the application, this route should respond with token so that it can be used in the remaining routes of the app

**Comment by codeHatcher** [comment]
Added a route /auths/authorize which takes a GUID and creates a user if he doesn't exist and responds with a token, if the user already exists it will just respond with the token <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by footnote** [comment]
Duplicate of #53
