### ISSUE TITLE
User's posts should be returned somewhere

### ISSUE THREAD

**Issue by footenote** [codeHatcher/lightTribe#42]
User's posts should be returned somewhere so that client side be able to view them in the user's profile, you can retrieve them in GET /users/{userId}/posts or in a separate link

**Comment by codeHatcher** [comment]
This route already exists at the route you listed. Can you clarify what you are looking for? It is also referenced in the integration guide.

Is the current route `GET /users/{userId}/posts not showing up for you?

**Comment by footenote** [comment]
Solved!
