### ISSUE TITLE
Permission for using FB developer

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#43]
We need permission to the following FB uid to be able to login via Facebook
571375803

**Comment by codeHatcher** [comment]
Can you add me as admin to that account so I can access it and make sure it works for us.

**Comment by footenote** [comment]
Do we have updates here?

**Comment by codeHatcher** [comment]
We need to get an app id setup for you and share it with you.

**Comment by codeHatcher** [comment]
@footnote added as admin to facebook app. App ID is 1658513671063290

**Comment by avishaan** [comment]
The solution to this was having you create an app. Please make sure I am an admin user as well. @ShadiFares

**Comment by footnote** [comment]
can you send me your facebook id
