### ISSUE TITLE
Route to allow the user to post his interests

### ISSUE THREAD

**Issue by footenote** [codeHatcher/lightTribe#45]
Now we have GET route to receive user's interests, but we don't have a route to post user's interests

**Comment by codeHatcher** [comment]
I think there is some confusion as to what the v1/interests route is. It doesn't retrieve the interests of the user, if it did it would follow the same convention of the other routes and would be called v1/users/{userid}/interests.

Instead the user interests updates are located here.
![image](https://cloud.githubusercontent.com/assets/5360982/8223737/b9f7dd1c-1530-11e5-98ca-1bfdf0d5c35c.png)

It's also cross referenced in the integrations guide.

**Comment by ShadiFares** [comment]
What we are looking for is: After a user is presented with a list of interest, Using the route GET /v1/interests, there is no route to send back the interests or categories the user has selected.

**Comment by codeHatcher** [comment]
Sorry, the image added was incorrect. Here is the correct one.
![screen region 2015-06-17 at 20 37 28](https://cloud.githubusercontent.com/assets/5360982/8224344/5b5b446a-153a-11e5-9d89-6ec2594fd3c2.png)

**Comment by footenote** [comment]
Solved!
