### ISSUE TITLE
Post new question responds with bad request

### ISSUE THREAD

**Issue by kwaheed** [codeHatcher/lightTribe#47]
POST v1/posts

**Comment by codeHatcher** [comment]
Can you send me information how to replicate this? I am not getting the same issue as you. Can you also share with me the exact response you are getting as that will help me debug the issue you are having?

Attached is what the response looks like for me.

![image](https://cloud.githubusercontent.com/assets/5360982/8223839/1d8199e4-1532-11e5-9e03-4cf9f4f7d50d.png)

**Comment by kwaheed** [comment]
Am I doing anything wrong?

![screen shot 2015-06-21 at 1 31 02 am](https://cloud.githubusercontent.com/assets/7980253/8269716/3db2a976-17b5-11e5-9057-7b706b71b26e.png)

**Comment by codeHatcher** [comment]
This is still working for me.

Can you try ```access_token = 8BY2mPWliL0iMMQeWx ``` and let me know what you get.

**Comment by kwaheed** [comment]
Worked!

**Comment by codeHatcher** [comment]
The token you had before, was it an anonymous token or from a registered user?

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Mon, Jun 22, 2015 at 6:42 PM, kwaheed <notifications@github.com> wrote:
Closed #47 [https://github.com/codeHatcher/lightTribe/issues/47] .

—
Reply to this email directly or view it on GitHub
[https://github.com/codeHatcher/lightTribe/issues/47#event-337340918] .[https://github.com/notifications/beacon/AFHNVnei65NlZ9SJWUahJXsxTJYJS-zgks5oWLD5gaJpZM4FC4Nc.gif]

**Comment by footenote** [comment]
Registered one
