### ISSUE TITLE
Radius reading timeline

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#48]
What is the value that I should set while getting the timeline items, my assumption that this should be a backend task.

**Comment by codeHatcher** [comment]
You should be passing in a radius in km which describes the MapKit View.

You could either use MKCircle with MKCircleView to overlay a circle onto the map which changes as the user zooms the map and return the radius from there.

Or more simple, don't overlay anything and just use the coordinates in view as the radius of the circle. A little calculation would be required but this should help you with that. I believe in MKMapView it is called "span" which you can use to calculate the approximate view. Check out the below for more information.

https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapView_Class/index.html#//apple_ref/occ/cl/MKMapView

**Comment by footenote** [comment]
We are still working on this, Will update when closed

**Comment by codeHatcher** [comment]
No problem, let us know if you have any questions.

**Comment by codeHatcher** [comment]
Let me know if you have any other questions on this.
