### ISSUE TITLE
Facebook authentication for an existing user through basic authentication

### ISSUE THREAD

**Issue by ShadiFares** [codeHatcher/lightTribe#49]
What is the business logic for a user used basic authentication, How should we merge the two accounts. 
Use case: 
A user already logged in and then enables the Facebook login. 
What is the front sending the backend that maintains the connection between the existing account and the new authentication through facebook.

**Comment by kwaheed** [comment]
![fb](https://cloud.githubusercontent.com/assets/7980253/8151176/cde3236c-1306-11e5-8514-2e1171322ec4.png)

**Comment by codeHatcher** [comment]
Good question, we are working on getting this answered. We will differentiate the notion of authenticating a user with the notion of "authorizing" a user. When we authorize the use of Facebook connection at the screen you are referencing above, we will connect the accounts by looking at the token passed in.

Note: this route we pick will most likely be different from the current Facebook route. Will keep you updated as we figure this out.

**Comment by footenote** [comment]
Do we have updates here?

**Comment by codeHatcher** [comment]
this is not in scope, closing out.
