### ISSUE TITLE
Push Notification Integration

### ISSUE THREAD

**Issue by ShadiFares** [codeHatcher/lightTribe#50]
Need the route for integrate push notifications

**Comment by codeHatcher** [comment]
Agreed, we will give you a route to add the UDID. We are currently working through updating the notification method we use to handle this.

**Comment by codeHatcher** [comment]
Can you send us the certs for the dev env? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kwaheed** [comment]
Sent via email

**Comment by codeHatcher** [comment]
Certificate is telling us we have incorrect password, can you confirm the password? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by footenote** [comment]
Oh, I will export it again with less complex password and will get back to you

**Comment by codeHatcher** [comment]
Feel free to export with as complex as you want. That is no problem as we are not typing it in, only copying and pasting it into the configuration variables.

**Comment by codeHatcher** [comment]
Received the update certificate. Will integrate into the server tonight. You will have a couple of notification routes exposed which you can begin playing with.

**Comment by codeHatcher** [comment]
This should be good to go. When a post is commented on, the author of the post will get a notification. You will be able to see that in the ios app. Let me know if you have any difficulty with this.
