### ISSUE TITLE
Check correct comment response includes thumbnail of user

### ISSUE THREAD

**Issue by codeHatcher** [codeHatcher/lightTribe#51]
![image](https://cloud.githubusercontent.com/assets/5360982/8223693/4e5b0336-1530-11e5-872d-b6205dc7d8de.png)

**Comment by footnote** [comment]
Any update here?

**Comment by footnote** [comment]
Need to include date of the comment in the format of timestamp to be able to display that the comment is  2 HRs ago
Also we need to sort the comments by most recent comments in the top of the array
