### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by footenote** [codeHatcher/lightTribe#52]
We tried the search route GET /v1/posts and found that the response is the same as the "terms" property doesn't contain any keyword, I mean that I think that whatever the keyword posted, the same data are being returned every time

**Comment by codeHatcher** [comment]
Yes, you are right. This is a backend issue that we will solve. You guys can keep developing with the assumption that this will work when in production. In the meantime make sure you are sending the "terms" to us.
