### ISSUE TITLE
User profile thumbnail in timeline

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#55]
We need to have the user image to be sent as URL in the response body of the GET /v1/posts in the user details

```javascript
{
_id: "559339ddfdd492140087250d",
text: "This is a very relavent post to Kareem",
createDate: "2015-07-01T00:52:45.766Z",
author: {
_id: "559078822075061400f2762d",
username: "sobhy"
},
__v: 0,
images: [
"55933965fdd492140087250b",
"55933995fdd492140087250c"
],
loc: {},
interests: [
"yogaBikram"
]
},
```

**Comment by codeHatcher** [comment]
Can you confirm this is an issue. You mentioned it in #68 as well but I couldn't find it there.

**Comment by footnote** [comment]
It works now, but we noticed that there are null values which may result to crash the app, please return an empty array instead

**Comment by codeHatcher** [comment]
I see you posted it in another place as well. I am going to close this thread so we can resume this convo in a single place.
