### ISSUE TITLE
Get participants of a post

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#56]
We need a route to receive post's participants

**Comment by footnote** [comment]
I noticed that the route is implemented
GET /v1/posts/{postId}/users

but it returns dummy data, we can't use these data to access user profile

**Comment by footnote** [comment]
Also we need the response of this url to be as documented in the model

Model Schema

```javascript
[
  {
    "username": "codeHatcher",
    "_id": "54f44c5d26352b1b9755b12f",
    "lastLogin": "2015-03-04T07:36:56.224Z",
    "userImage": {
      "url": "https://www.google.com/images/srpr/logo11w.png"
    }
  }
]
```

Real Response 
```javascript
[
  {
    "_id": "100",
    "user": {
      "username": "codehatcher",
      "lastLogin": 1436145279484,
      "thumbnail": "https://www.google.com/images/srpr/logo11w.png"
    }
  },
  {
    "_id": "101",
    "user": {
      "username": "codehatcher",
      "lastLogin": 1436145279484,
      "thumbnail": "https://www.google.com/images/srpr/logo11w.png"
    }
  }
]
```

**Comment by codeHatcher** [comment]
Updated and matching the docs. Releasing in a few minutes.

**Comment by footnote** [comment]
This the model schema

```javascript
[
  {
    "username": "codeHatcher",
    "_id": "54f44c5d26352b1b9755b12f",
    "lastLogin": "2015-03-04T07:36:56.224Z",
    "userImage": {
      "url": "https://www.google.com/images/srpr/logo11w.png"
    }
  }
]
```

and this is the response

```javascript
[
  {
    "_id": "559078822075061400f2762d",
    "username": "sobhy"
  },
  {
    "_id": "559078822075061400f2762d",
    "username": "sobhy"
  },
  {
    "_id": "559078822075061400f2762d",
    "username": "sobhy"
  }
]
```

They are not matching each other.

**Comment by codeHatcher** [comment]
Can you give me the steps to replicate this issue?

**Comment by codeHatcher** [comment]
I actually don't see this userId in the database so I can't replicate the issue.

**Comment by footnote** [comment]
Route = GET: /v1/posts/{postId}/users
post_id = 558dd5c15c99c61400e2c69c
access_token = S362u7bFRqRvJo53Zv
page = 1

**Comment by footnote** [comment]
Add CodeHatcher - This is the one we talked about on the phone

**Comment by codeHatcher** [comment]
Still can't replicate, even added an extra test.

**Comment by codeHatcher** [comment]
wait, I just did this and got this response. @ShadiFares Any idea why you are getting something different?
<img width="818" alt="screen region 2015-09-14 at 23 38 00" src="https://cloud.githubusercontent.com/assets/5360982/9867254/a7b2ad18-5b39-11e5-80b8-ffab7bf6a0cb.png">

**Comment by codeHatcher** [comment]
@footnote let me know if you are getting different results from me.

**Comment by footnote** [comment]
Now it works, but I noticed in your screenshot that it returns a null value, this may results to crashing the app, please return an empty array

**Comment by codeHatcher** [comment]
please see #68 Your request is the same issue there. In this case, the front end didn't attach a user image therefore there is no user therefore we will return null.
