### ISSUE TITLE
Need clarification to the map indicator in the search text field

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#59]
Attached
<img width="266" alt="screen shot 2015-07-05 at 3 50 43 am" src="https://cloud.githubusercontent.com/assets/7980253/8509989/314ed582-22c9-11e5-86c7-530ed3653b16.png">

**Comment by codeHatcher** [comment]
This should open up the map view so that the user can pick a location and radius.

**Comment by codeHatcher** [comment]
This discussion of the mapview is slightly relevant as well. #48
