### ISSUE TITLE
Need to separate user settings route

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#60]
We need a separate route for updating user interests as well as another route for uploading user image, as in the design they are in different screens.

The route that should be separated POST /v1/users/{userId}

I believe that the resulted routes should be 

1- POST /v1/users/{userId}/interests

Suggested Request Body

```javascript
{
  "interests": [
    "bikramYoga1",
    "bikramYoga2"
  ]
}
```
2- POST /v1/users/{userId}/image

Suggested Request Body
```javascript
{
  "userImage": "5572286715404b55c47017b7"
}
```

**Comment by codeHatcher** [comment]
Any reason we need to separate this? You can use the same route for either updating interests or updating the user image.

**Comment by ShadiFares** [comment]
Does it allow the user to update only his image using this route ? And not submit interests details?

**Comment by codeHatcher** [comment]
Only the items passed in are updated. If you pass in only the interests, then the interests are updated. If you pass in interest and userImage, then both are updated.

**Comment by footnote** [comment]
Sounds good
