### ISSUE TITLE
Respond with usertoken in register new user route

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#61]
Is it possible to send the token of the user in the response of Post v1/users to allow the user to use the application without needing to authenticating after registration? It would better from user experience perspective.

Hint: this scenario has been applied in Quipics, we were allowing the user to use the application just after the registration.

**Comment by codeHatcher** [comment]
Yes, I think so. Because we are not sending an email confirmation this should be acceptable. If we ever move over to email required before sign up this would have to change and we would have to stop doing this but I don't think that's a real issue.

**Comment by codeHatcher** [comment]
Added token
