### ISSUE TITLE
Need route to report inappropriate image

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#62]
As for Apple License agreement we need to have a route to report inappropriate images

**Comment by codeHatcher** [comment]
I don't think we want to report images. I think we will want to report on the post so that we can remove everything if there is an issue

**Comment by footnote** [comment]
Does make sense

**Comment by codeHatcher** [comment]
We have a placeholder route in place. It's not hooked up but the interface should remain consistent.
