### ISSUE TITLE
Implement block route

### ISSUE THREAD

**Issue by codeHatcher** [codeHatcher/lightTribe#76]
Block route is asked for implementation but there is currently no consequence of a block so we will not be implementing this.

**Comment by codeHatcher** [comment]
#71

**Comment by footnote** [comment]
i am not sure, but i think it might be important to implement the route even if nothing happens on the backend so that we don't get a rejection from appstore

**Comment by codeHatcher** [comment]
Ok, will do.

**Comment by codeHatcher** [comment]
We are not sure what to do for the block route. What would the block route be used for? That might help us design/develop the route.

**Comment by sobhy** [comment]
@codeHatcher I believe the block route should prevent the blocked user to see the blocker user, and not to see his posts too...
Also in following this user.

If you have anything else, please suggest

**Comment by codeHatcher** [comment]
relatively complex but at least we can put the route in and then start using the data later on to manipulate the data the routes return.

We will get on this.

**Comment by codeHatcher** [comment]
Talked about this on the phone with @ShadiFares, use the currently available reporting route by passing in the document type (user, comment, post, message) plus the associated id.

**Comment by codeHatcher** [comment]
I think we finalized this decision. There are no test cases for this currently but it should be good enough for the first pass.
