### ISSUE TITLE
Integration Documentation with Socket is required

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#78]
We need the following information to be able to integrate with Socket:

-Base URL
-IP
-Is user authentication is required before connecting with socket? What are the parameters to be sent?

**Comment by codeHatcher** [comment]
Checkout the front page README for the documentation. No authentication is required since we are not sending the payload.

**Comment by footnote** [comment]
-Base URL
-IP

These parameters are not available in the docs
