### ISSUE TITLE
Conversation ID needed in post details

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#80]
In post details, the conversation ID is needed to be able to to retrieve conversation history in case the user does have history with the invited participant, and in case he doesn't have history, this key should be set as null

**Comment by codeHatcher** [comment]
When creating a message we need to return the conversation id to the front end.

**Comment by footnote** [comment]
Where can I find the conversation id?

**Comment by codeHatcher** [comment]
I believe this is the same as #100 based on our conversation.

**Comment by footnote** [comment]
correct
