### ISSUE TITLE
Light Page event type types (workshop, meeting, etc) while creating a page route is needed

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#81]
As per pur conversation, we need a route for displaying types of light page that are going to be used while creating a light page

**Comment by codeHatcher** [comment]
sorry, types of lightpage?

**Comment by footnote** [comment]
I believe Kareem was referring to the type of the event to be created as per the drop down in the  mockup. the list of events (workshop, ...etc)

**Comment by codeHatcher** [comment]
Ah, gotcha, related to pulling the list of event types from the backend. Got it. I'm going to update the title a little bit to reflect that.

**Comment by footnote** [comment]
Updates?

**Comment by codeHatcher** [comment]
@ShadiFares @footnote there is a new header in the docs called "categories" where you can go to get interestsTypes, eventTypes, and any future types that we may need for the system. The old interests routes is still there for backward compatibility.
