### ISSUE TITLE
Implementing user as anonymous isn't working

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#86]
It's expected to be able to hit the routes with anonymous users, I should be able to access the routes using the iPhone token, when I tried to access GET /v1/posts with iPhone token, the route responded with unauthorized...
Is there a way to implement anonymous users different than this?

**Comment by codeHatcher** [comment]
That's not how the anonymous authentication works. Please check the docs under
/auth/anonymous.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Sun, Oct 11, 2015 at 1:45 PM, footnote.consulting <notifications@github.com>
wrote:
Assigned #86 [https://github.com/codeHatcher/lightTribe/issues/86] to @codeHatcher [https://github.com/codeHatcher] .

—
Reply to this email directly or view it on GitHub
[https://github.com/codeHatcher/lightTribe/issues/86#event-432464237] .[https://github.com/notifications/beacon/AFHNVhJpUCXaMnwZFdf2dL5gqnyUHeEvks5o6sIGgaJpZM4GM0NL.gif]

**Comment by footnote** [comment]
It's crashing...

<img width="483" alt="screen shot 2015-10-14 at 12 17 58 am" src="https://cloud.githubusercontent.com/assets/7980253/10469880/268173aa-7209-11e5-88ef-537d415d461d.png">

**Comment by codeHatcher** [comment]
As per an email received we will no longer be doing this. Please keep the code for future use as it may be added on in the future.
