### ISSUE TITLE
GET Profile is crashed

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#87]
link GET/v1/profiles/{userId} is crashed right now as shown below

Testing data
 "_id": "561d80873412516e01bdf0f4",
  "token": "3CyYylQBPLHgtbA39Z"

<img width="489" alt="screen shot 2015-10-14 at 12 10 07 am" src="https://cloud.githubusercontent.com/assets/7980253/10469759/24a8d70e-7208-11e5-899b-db616c8ea75c.png">

**Comment by footnote** [comment]
http://lighttribe-dev.herokuapp.com/api/v1/profiles/561d80873412516e01bdf0f4?access_token=3CyYylQBPLHgtbA39Z

**Comment by codeHatcher** [comment]
might be related to #84 looking into this now.
