### ISSUE TITLE
GET /v1/conversations is responding with image id instead of image URL

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#91]

**Comment by footnote** [comment]
Still getting this response 

Try to hit this url:
http://lighttribe-dev.herokuapp.com/api/v1/conversations?access_token=S362u7bFRqRvJo53Zv

```javascript
{
_id: "560073deb0fa221400aa3371",
__v: 0,
participants: [
{
_id: "5599bfa6be10e91400dabbc3",
username: "sob",
password: "$2a$09$vLTup3mTIEF9GFD/WdWgJ.VZhtOE7lsmLZZt1ZNpRjxJ3UQanX.q6",
__v: 3,
userImage: "561fdfd0205a6514006cdeef",
follows: [
"54f44c5d26352b1b9755b12f",
"56192c92d53c0a4500989c84"
],
devices: [ ],
interests: [
"Yoga",
"Rugby"
],
profile: {
shortDescription: "Fill in the service you have to offer"
},
token: {
expires: "2015-07-05T23:37:10.511Z",
value: "S362u7bFRqRvJo53Zv"
}
}
],
createDate: "2015-09-21T21:17:18.663Z"
},
```

**Comment by codeHatcher** [comment]
Thanks for sharing the route, makes it easier to look into.

**Comment by codeHatcher** [comment]
Stuck on this, can't figure out why our test cases pass but this example data you shared doesn't populate.

**Comment by codeHatcher** [comment]
Oh I see, on the phone you described this route as getting a specific conversation. Not getting the list of conversations. That's why it still doesn't work for you because the route you described on the phone was fixed, not this one.

**Comment by codeHatcher** [comment]
This turns out to be one of the most computationally expensive queries, if we don't get up using the thumbnails when looking at the list of conversations let's revisit this and potentially remove that population step. For now we will go ahead and implement this.

**Comment by codeHatcher** [comment]
![image](https://cloud.githubusercontent.com/assets/5360982/10539535/00382696-73b5-11e5-91a8-7fe5183660d3.png)
