### ISSUE TITLE
Route to get all users needed

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#94]
A route to get all users saved in the app is needed with a flag to show if I' following that user or not. My user profile should not be returned in users list

**Comment by footnote** [comment]
@footnote we will note need a route to retrieve all users. we are only following users from a certain post (based on liking what they said) and not through looking them

**Comment by codeHatcher** [comment]
Can we close this out?

**Comment by codeHatcher** [comment]
@ShadiFares @footnote can we close this out?

**Comment by codeHatcher** [comment]
@footnote can we close this out?

**Comment by footnote** [comment]
yes. ok to close
