### ISSUE TITLE
User image needs to be returned in user posts GET /v1/users/{userId}/posts

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#97]
As in the mockup, the client needs the image of the user to be returned in the user posts

**Comment by codeHatcher** [comment]
@footnote the api seems to already be passing back the information. I went ahead and updated the docs for you.

**Comment by codeHatcher** [comment]
@footnote the api seems to already be passing back the information. I went ahead and updated the docs for you.
