### ISSUE TITLE
User image required to be returned in list of follows

### ISSUE THREAD

**Issue by footnote** [codeHatcher/lightTribe#99]
POST /v1/users/{userId}/follows

**Comment by codeHatcher** [comment]
I think you mean't this to be `POST /v1/users/{userId}/follows` so I will assume that to be the case.

**Comment by codeHatcher** [comment]
can you confirm this is still an issue? This looks the same as #94 and wasn't sure.

**Comment by codeHatcher** [comment]
This looks the same as #93 which was closed out. This of course is assuming my assumption about which route you mean't is correct. Please confirm. @footnote

**Comment by footnote** [comment]
correct
